import Head from "next/head"
import Image from "next/image"
import Heading from "../Components/UI/Heading"

export default function Home() {
  return (
    <>
      <Head>
        <title>Chalet | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main className="container">
        <div className="relative flex flex-col justify-center items-center mt-6 lg:mt-16 ">
          <Image
            src={"/landing.png"}
            width={450}
            height={450}
            alt="image"
            className="drop-shadow-2xl animate-HorizentalMove"
          />

          <Heading title="wellcome to my" highLightText="Portfolio" />
        </div>
      </main>
    </>
  )
}
