import Head from "next/head"
import Landing from "../Containers/Home/landing"
import SkillsCards from "../Containers/Home/SkillsCards"
import CV from "../Containers/Home/CV"
import Hero from "../Containers/Home/Hero"
import Contact from "../Containers/Home/Contact"

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main className="container mb-24">
        <Landing />

        <SkillsCards />

        <CV />

        <Hero />

        <Contact />
      </main>
    </>
  )
}
